### ISSUE TITLE
Ingest/storage lock to prevent concurrent updates

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#532] opened 2020-11-23 17:19 UTC
Ingest/storage requests are increasing. We are seeing more and more overlapping / concurrent requests on the same object.  From my perspective the damage from concurrent requests now outweighs the earlier rarity of this happening. One question that is related, is whether this should also be viewed as process to centrally log the start and stop of ingest/storage(/inv).

One recent incident is a typical case of how things can go wrong:
~~~
s1-start-19-Nov-2020 11:08:47.882 INFO [http-nio-35121-exec-417] 
s1-stop -19-Nov-2020 11:26:16.198 INFO [http-nio-35121-exec-417] 
i2-proc  19-Nov-2020 11:26:42 PST 2020 - OK - version 2
......
s2-start 19-Nov-2020 11:22:11.325 INFO [http-nio-35121-exec-429]
s1-start-19-Nov-2020 11:29:28.772 INFO [http-nio-35121-exec-407] 
s1-stop -19-Nov-2020 11:30:45.725 INFO [http-nio-35121-exec-407]
i2-proc  19-Nov-2020 11:31:44 PST 2020 - OK - version3
...
s2-stop  19-Nov-2020 11:33:10.253 INFO [http-nio-35121-exec-429] - replaces 3 version manifest with version 2
i1-proc- 19-Nov-2020 11:33:37 PST 2020 - failed - clobbered manifest version 2 - inv version 3

s1-store01-prd
s2-store02-prd
i1-inventory01-prd
i2-inventory02-prd
~~~

Several different approaches need to be reviewed:
- if all storage servers share the same temp storage then a common flag can be used
- a shared common s3 location can be used for flags - will require some failed process handling for cleanup
- a shared common MySQL entry - could be leveraged into a general submission status record - could tie into  existing request to localids table set by inventory

**Comment by mreyescdl** [comment] 2020-11-24 03:10
Removed object ark:/13030/m57d82qz from production and reprocessed feed
New object is:

https://merritt.cdlib.org/m/ark%253A%252F13030%252Fm5q86wxs

Note:  Have not yet altered Nuxeo feed yet.  
production-27012-UCCE-ucm_lib_ucce_merced.csh

**Comment by mreyescdl** [comment] 2020-11-24 19:33
Fix is in for Nuxeo process.
To explain problem, lets look at how Nuxeo processing is launched.  They are crond with a lock being created for each collection submission (using Linux utility "flock".)  If the lock exists (meaning active processing) we wait until lock is cleared.  The processing for Merced county took three weeks, two subsequent processes were waiting for lock to clear.
Once cleared, feed reprocessed every object that had not yet been updated in DB (Inventory.)  This was only one object.

The fix was to change the "flock" command to not wait for lock to clear, but instead just exit using the --no-block option.  e.g.

/usr/bin/flock -n /dpr2/apps/ui/atom/LockFile/UCM_LibraryDSC.lock

**Comment by mreyescdl** [comment] 2020-11-24 21:47
Note:  A lock on the Ingest service would not have prevented this error.

There are two type of race conditions we may see and no single service lock addresses both (I believe)
- Ingest completes, but Inventory has not yet updated DB and Ingest submits another version.  [DB-Inv out of sync error]
- Ingest submits two version of object concurrently. [Storage error or no error and only 1 version]

**Comment by elopatin-uc3** [comment] 2022-01-03 17:48
Noting https://github.com/CDLUC3/mrt-doc/issues/875

**Comment by elopatin-uc3** [comment] 2022-01-04 03:08
Closing as duplicate of #875

**Closed by elopatin-uc3** 2022-01-04 03:08 UTC
Labels: storage
