### ISSUE TITLE
[Ingest] Local ID lock 

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#909] opened 2022-01-18 22:32 UTC
During Storage concurrency test we found that the Local ID registration can raise an exception.
Overlapping registration of Local ID for the same object causes the exception.

Creating a lock prior to registration is the simple solution, but unfortunately at the time of calling we are not yet guaranteed to have a unique primary ID (ark) to use as a lock ID.
Consider using a combination of "Owner and Local ID" as a new lock ID.

**Comment by elopatin-uc3** [comment] 2022-01-19 00:17
Related to the following tickets:
#873, #875, #907, #908

**Comment by elopatin-uc3** [comment] 2024-11-06 20:45
Closing as duplicate of #2029

**Closed by elopatin-uc3** 2024-11-06 20:45 UTC
Labels: ingest, zookeeper
