### ISSUE TITLE
Updating the TLS endpoint version

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1421] opened 2023-04-06 20:04 UTC
Hello,

We are reaching out because there are TLS 1.0 or TLS 1.1 connections to Amazon Simple Storage Service (Amazon S3) objects hosted in your account. As AWS is updating the TLS configuration for all AWS API endpoints to a minimum of version TLS 1.2 [1], you must take action as soon as possible for these connections to maintain their access to your S3 objects.

What actions can I take to maintain access?
To avoid potential interruption, you must update all client software accessing your Amazon S3 objects using TLS 1.0 or 1.1, to use TLS 1.2 or higher. If you are unable or would prefer to not update all impacted clients, we recommend replacing direct client access to the S3 objects with use of a proxy, such as an Amazon CloudFront distribution. This will allow clients to access your S3 objects via Amazon CloudFront using any TLS version you choose to allow. Amazon CloudFront will forward the calls to your S3 objects using TLS 1.2 or higher. For more guidance for how to setup your CloudFront distribution to front your S3 object access, please review this Knowledge Center article [2].

How can I determine the client(s) I need to update?
We have provided the affected S3 bucket(s) in your account at the end of this message. In order to gather additional information about the affected objects and user agents performing these calls, we recommend enabling Amazon CloudTrail data events on the affected S3 bucket(s) [3] [4]. The information contained in the S3 data events will help you pinpoint your client software that is responsible for using TLS 1.0 or TLS 1.1, so you may update it accordingly. Additionally, our related AWS Security blog post [1] provides information on how you may use TLS information in the CloudTrail tlsDetails field. Please note there is an associated cost for enabling CloudTrail data events, please see the CloudTrail pricing page for more detail [5].

How can I enforce connections to my bucket(s) be over TLS 1.2 and above?
As a best practice, and to prepare for our enforcement of TLS 1.2 or higher, we recommend you proactively enforce a minimum of TLS 1.2 directly on all of your shared S3 bucket(s). You may do this by applying a bucket policy with the s3:TlsVersion condition key as per the documented this Knowledge Center article [6]

If you need further guidance or assistance, please contact AWS Support [7] or your Technical Account Manager.

[1] https://aws.amazon.com/blogs/security/tls-1-2-required-for-aws-endpoints
[2] https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-old-tls/
[3] https://docs.aws.amazon.com/AmazonS3/latest/userguide/cloudtrail-logging-s3-info.html#cloudtrail-object-level-tracking
[4] https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-cloudtrail-logging-for-s3.html#enable-cloudtrail-events
[5] https://aws.amazon.com/cloudtrail/pricing/
[6] https://aws.amazon.com/premiumsupport/knowledge-center/s3-enforce-modern-tls/
[7] https://aws.amazon.com/support

Please see the following for S3 buckets in which object-level calls were made over TLS 1.0 or TLS 1.1 connections between March 27, 2023 and April 04, 2023 (the UserAgent may be truncated due to a limit in the number of characters that can be displayed):

Connections details will be in the following format:
Region | Bucket name(s) | APIAction | TLSVersion | NumCalls | UserAgent
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|32|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|148|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.95 Safari/537.
us-west-2|uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|17|[Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|104|[Mozilla/5.0 (Windows NT 10.0; WOW64)
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|88|[Mozilla/5.0 (Windows NT 10.0; WOW64)
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|38|[Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36]
us-west-2|uc3-s3mrt5001-prd,uc3-s3mrt5001-prd | REST.GET.OBJECT|TLSv1|3|[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|27|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.95 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|45|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.95 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|111|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.42
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|151|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|98|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.95 Safari/537.3
us-west-2|uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|57|[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|17|[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|31|[Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|131|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|56|[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|50|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|7|[Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.95]
us-west-2|uc3-s3mrt1001-prd,uc3-s3mrt1001-prd | REST.GET.OBJECT|TLSv1|44|[Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.95 Safari/537.36]

Sincerely,
Amazon Web Services

**Comment by elopatin-uc3** [comment] 2023-04-07 15:16
Closing as duplicate of #25.

**Closed by elopatin-uc3** 2023-04-07 15:16 UTC
