### ISSUE TITLE
Reset sql connection in audit when processing a large batch

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#698] opened 2021-06-11 15:47 UTC
Copied from a conversation with @dloy  on Slack:

>  for extremely long runs, the old mysql connection is not tested to be valid. Have a fix that if time is > 1 hour than test if valid and reset if not

Note that this should prevent the "null batch" issue that has been appearing in the "audit size of queue" report.

https://merritt-admintool.cdlib.org/index.html?path=audit_size

**Comment by elopatin-uc3** [comment] 2021-06-11 16:28
Closing as duplicate of #699

**Closed by elopatin-uc3** 2021-06-11 16:28 UTC
Labels: audit
