### ISSUE TITLE
Stage steps delete swift

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#215] opened 2020-01-21 23:43 UTC
# Stage Phase 2 swift to minio migration
Phase 2 of the swift to minio migration involves the removal of all swift references from the inv db.

This phase does not involve any downtime for Merritt. It will require restarts of all Merritt back end servers that use the inv db: inventory, replic, and audit.
## Steps
* stop stage replic and audit services
* delete swift nodes in inv db
* restart inv
* restart services

Modified inv database:
_uc3db-inv-stg.cdlib.org_
## stop stage replic and audit services
- [ ] (Debra) Checkpoint db
- [ ] (Mark) Shutdown stage monitors
* Monitors for stage replication - uc3-mrtreplic2-stg
* Monitors for stage inventory - uc3-mrtinv-stg, uc3-mrtinv2-stg
* Monitors for stage audit - uc3-mrtaudit-stg
- [ ] (David) Shutdown stage replic and audit
* issue replic shutdown
* issue audit shutdown
## delete swift nodes in inv db
- [ ] (David) Run delete script for swift nodes
- [ ] (David) Run confirmation script for deleted swift
## restart services
- [ ] (David) Restart stage replic and audit
- [ ] (Mark) server restarts servers on inventory
This is to guarantee no db caching.  Requires drain and restart
- [ ] (Mark) Restart monitors inventory, replic, audit

**Comment by elopatin-uc3** [comment] 2020-01-31 18:50
Closing as duplicate of #222 .

**Closed by elopatin-uc3** 2020-01-31 18:50 UTC
Labels: Tools & Processes, migration
