### ISSUE TITLE
Some Merritt failures (I think ones going through from 2-3 today)

### ISSUE THREAD

**Issue by sfisher** [CDLUC3/mrt-doc#955] opened 2022-03-09 02:04 UTC
Around 2-2:30 pm on Tuesday (just before maintenance) Dryad had some submission failures.  It was around the time Mark mentioned he was deploying something.  After maintenance from 4-5:30 tried to resubmit  and 12 datasets still fail to go through and still give errors.

The errors in our logs from Merritt are like these

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error href="Ingest handling failure url='http://ingest.cdlib.org:33121/ingest/update-object' Exception:org.swordapp.server.action.IngestHandler-setIngestRespons
e:275 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] HTTPUTIL: getObject- Error during HttpClient processing - responseCode:500" xmlns:sword="http://purl.org
/net/sword/terms/"><atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title><atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2022-03-08T17:40:37Z</
atom:updated><atom:generator uri="http://www.swordapp.org/" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"/><sword:treatment>Processing failed</sword:treatment
><atom:summary xmlns:atom="http://www.w3.org/2005/Atom">Ingest handling failure url='http://ingest.cdlib.org:33121/ingest/update-object' Exception:org.swordapp.server.
action.IngestHandler-setIngestResponse:275 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] HTTPUTIL: getObject- Error during HttpClient processing - responseC
ode:500</atom:summary><sword:verboseDescription>org.swordapp.server.SwordError: Ingest handling failure url='http://ingest.cdlib.org:33121/ingest/update-object' Except
ion:org.swordapp.server.action.IngestHandler-setIngestResponse:275 EXTERNAL_SERVICE_UNAVAILABLE[Unavailable remote service] HTTPUTIL: getObject- Error during HttpClien
t processing - responseCode:500
        at org.swordapp.server.action.IngestHandler.process(IngestHandler.java:133)
        at org.swordapp.server.action.MerrittContainerManager.process(MerrittContainerManager.java:231)
        at org.swordapp.server.action.MerrittContainerManager.process(MerrittContainerManager.java:157)
        at org.swordapp.server.action.MerrittContainerManager.replaceMetadataAndResources(MerrittContainerManager.java:105)
        at org.swordapp.server.ContainerManagerImpl.replaceMetadataAndMediaResource(ContainerManagerImpl.java:34)
        at org.swordapp.server.ContainerAPI.put(ContainerAPI.java:210)
        at org.swordapp.server.servlets.ContainerServletDefault.doPut(ContainerServletDefault.java:55)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
</sword:verboseDescription></sword:error>
```

These are the 12:

resource_id  and doi
140204	doi:10.5068/D1QX0W
167205	doi:10.5061/dryad.jm63xsjcw
167207	doi:10.6078/D18M5V
167208	doi:10.5061/dryad.v9s4mw6xv
167206	doi:10.7280/D1PQ5N
167212	doi:10.6086/D14M41
167214	doi:10.5061/dryad.gb5mkkwrn
167209	doi:10.5061/dryad.7wm37pvvw
167211	doi:10.5061/dryad.dz08kprz7
167218	doi:10.5061/dryad.nvx0k6dtx
167225	doi:10.25338/B8FW6R
167220	doi:10.5061/dryad.gf1vhhmqn

**Comment by elopatin-uc3** [comment] 2022-03-09 21:29
Thanks for reporting this @sfisher . Now that the dataset objects in question have been processed, I'm going to go ahead and close this ticket. We believe the root cause can be attributed to the Ingest changes that were deployed and rolled back. More information can be found in Mark's latest comment in #949 (re: the updated JDOM artifact).

**Closed** 2022-03-09 21:29 UTC
Labels: ingest, dryad
