### ISSUE TITLE
UCR Nuxeo feed: Hiram N. Savage papers

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1623] opened 2023-09-29 18:46 UTC
Source ticket: https://help.oac.cdlib.org/a/tickets/127696

Collection Registry entry created:
https://registry.cdlib.org/admin/library_collection/collection/26752

ATOM feed:
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_26752.atom

Root folder in Nuxeo:
/asset-library/UCR/SCUA/Archival/Hiram Newton Savage papers

Merritt collection: EXISTING:
UC Riverside Library Nuxeo collection
ark:/13030/m5qg11t8

**Comment by mreyescdl** [comment] 2023-10-02 23:23
@elopatin-uc3 This Atom feed is exactly the same as Historical Archive collection
```
https://s3.amazonaws.com/static.ucldc.cdlib.org/merritt/ucldc_collection_27117.atom
```

Should I post this to the Nuxeo/Merritt channel?

**Comment by elopatin-uc3** [comment] 2023-10-02 23:41
Thanks for catching this @mreyescdl . Yes, please post this to the Nuxeo/Merritt channel.

**Comment by mreyescdl** [comment] 2023-10-03 17:03
- Created script
- Ran, but defined feed is a duplicate of previous UCR collection
- Waiting for fix of ATOM feed

**Comment by mreyescdl** [comment] 2023-10-11 16:11
- Feed has been altered
- Ran manually (2 objects)
- Scheduled for weekly processing

Complete

**Closed** 2023-10-20 20:46 UTC
Labels: atom - nuxeo, Sprint 93
