### ISSUE TITLE
UCB ingest failures on 5/20 - 5/21

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#333] opened 2020-05-26 20:10 UTC
Testing submitting all objects to Merritt Demo; no issues

Mark will create a ticket to document all observed information during investigation, in case this occurs again.

EL will confirm if lack of local IDs on half of objects was intended.

Not able to reproduce. Original submission took 12 hours. Submission to Demo took 4 hours. There was a lot going on during the 12 hour period.

**Comment by elopatin-uc3** [comment] 2020-05-26 22:02
David T at UCB has confirmed that the lack of local IDs for some manifest entries is expected. Reason being that some objects did not have call numbers to include.

**Comment by mreyescdl** [comment] 2020-05-26 23:48
Link to ticket with details of the problem
https://github.com/CDLUC3/mrt-doc/issues/334

**Comment by elopatin-uc3** [comment] 2021-03-05 23:11
Closing as duplicate of #334.

**Closed by elopatin-uc3** 2021-03-05 23:11 UTC
Labels: operations-board
