### ISSUE TITLE
Implement ingest hold at an owner/localid level

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#681] opened 2021-05-24 19:40 UTC
David recommended this while working on the Dash/Dryad migration effort.

Rather than holding an entire ingest queue, implement a feature to reject object level updates while maintenance is underway for an object.

**Comment by elopatin-uc3** [comment] 2021-07-20 22:09
Closing as duplicate of #532

**Closed by elopatin-uc3** 2021-07-20 22:09 UTC
Labels: inventory
